### ISSUE TITLE
页面导入样式的时候，使用link和@import有什么区别

### ISSUE THREAD

**Issue by QingyiHuang** [QingyiHuang/dailyYoung#1]
### 稍微花花时间，今天目标：解决两三个问题，减肥。今天还得做公司的项目，毕业典礼要开始了，我该怎样结束我的青春？(牢骚下，我真的很想要自由)

1. ##### 页面导入样式的时候，使用link和@import有什么区别

- link是HTML标签，@import是css提供的。
- link引入的样式页面加载时同时加载，@import引入样式需要等页面加载完毕之后再进行加载
- link没有兼容性问题，@import不兼容ie5以下。
- link可以通过js操作dom动态引入样式表改变样式，而@import不行
- 链接样式是HTML头部标签引入外部CSS文件

```html
<head>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
```

- 导入样式是使用CSS规则引入外部CSS文件

```css
<style>
    @import url(style.css);
</style>
/**或是在css样式中import**/
@charset "utf-8";
@import url(style.css);
*{ margin:0; padding:0;}
.notice-link a{ color:#999;}
```
